---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
namespace: dagster
resources:
  - test-helmrelease.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml