---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dagster
resources:
  - my-release.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml


  